###FILE: bibcat_parameters.py
###PURPOSE: Container for parameters.

##Import necessary packages
import bibcat_classes as bibcat

##Mission parameters
keyword_obj_BEFS = bibcat.Keyword(
            keywords=["Berkeley Extreme and Far-UV Spectrometer", "Berkeley Spectrometer"],
            acronyms=["BEFS"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_Copernicus = bibcat.Keyword(
            keywords=["Copernicus"],
            acronyms=["OAO-3", "OAO3"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_EUVE = bibcat.Keyword(
            keywords=["Extreme Ultraviolet Explorer"],
            acronyms=["EUVE"],
            banned_overlap=[],
            ambig_words=[])
#keyword_obj_FIRST = bibcat.Keyword(
#            keywords=[],
#            acronyms=["FIRST"],
#            banned_overlap=[])
keyword_obj_FUSE = bibcat.Keyword(
            keywords=["Far Ultraviolet Spectroscopic Explorer"],
            acronyms=["FUSE"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_GALEX = bibcat.Keyword(
            keywords=["Galaxy Evolution Explorer"],
            acronyms=["GALEX"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_HLA = bibcat.Keyword(
            keywords=["Hubble Legacy Archive", "Hubble Source Catalog"],
            acronyms=["HLA"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_HSC = bibcat.Keyword(
            keywords=[],
            acronyms=["HSC"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_HST = bibcat.Keyword(
            keywords=["Hubble", "Hubble Telescope", "Hubble Space Telescope"],
            acronyms=["HST", "HT"],
            banned_overlap=["Hubble Legacy Archive"],
            ambig_words=["Hubble"])
keyword_obj_HST_expanded = bibcat.Keyword(
            keywords=["Hubble", "Hubble Telescope", "Hubble Space Telescope", "10.17909", "Hubble Frontier Fields", "Hubble Frontier Field", "Advanced Camera for Surveys", "Wide Field Camera", "Wide Field Planetary Camera", "Space Telescope Imaging", "High Speed Photometer", "Goddard High-Resolution Spectrograph", "Faint Object Camera", "Hubble Fine Guidance Sensor", "Hubble FGS", "HST FGS"],
            acronyms=["HST", "HT", "HFF", "ACS", "GOODS", "HUDF", "HDF", "WFC3", "WFPC", "WFPC-1", "WFPC1", "WFPC2", "STIS", "NICMOS", "GHRS", "FOS", "FOC", "CANDELS"],
            banned_overlap=["Hubble Legacy Archive"],
            ambig_words=["Hubble"])
keyword_obj_HUT = bibcat.Keyword(
            keywords=["Hopkins Ultraviolet Telescope"],
            acronyms=["HUT"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_IMAPS = bibcat.Keyword(
            keywords=["Interstellar Medium Absorption Profile Spectrograph"],
            acronyms=["IMAPS"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_IUE = bibcat.Keyword(
            keywords=["International Ultraviolet Explorer"],
            acronyms=["IUE"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_JWST = bibcat.Keyword(
            keywords=["James Webb Space Telescope", "James Webb Telescope", "Webb Space Telescope", "Webb Telescope"],
            acronyms=["JWST", "JST", "JT"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_JWST_expanded = bibcat.Keyword(
            keywords=["James Webb Space Telescope", "James Webb Telescope", "Webb Space Telescope", "Webb Telescope", "NIRCam", "NIRSpec", "JWST FGS"],
            acronyms=["JWST", "JST", "JT", "Q3D", "CEERS", "MIRI", "NIRISS"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_Kepler = bibcat.Keyword(
            keywords=["Kepler"],
            acronyms=[],
            banned_overlap=[],
            ambig_words=["Kepler"])
keyword_obj_K2 = bibcat.Keyword(
            keywords=["K2"],
            acronyms=[],
            banned_overlap=[],
            ambig_words=["K2"])
keyword_obj_PanSTARRS = bibcat.Keyword(
            keywords=["Panoramic Survey Telescope and Rapid Response System", "Pan STARRS", "Pan-STARRS", "PanSTARRS-1", "Pan-STARRS1", "Pan-STARRS-1"],
            acronyms=["PanSTARRS", "PanSTARRS1", "PS1"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_Roman = bibcat.Keyword(
            keywords=["Roman", "Roman Telescope", "Roman Space Telescope", "Wide-Field Infrared Survey Telescope", "Wide Field Infrared Survey Telescope"],
            acronyms=["WFIRST", "RST", "NGRST"],
            banned_overlap=[],
            ambig_words=["Roman"])
keyword_obj_TESS = bibcat.Keyword(
            keywords=["Transiting Exoplanet Survey Satellite"],
            acronyms=["TESS"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_TUES = bibcat.Keyword(
            keywords=["Tubingen Ultraviolet Echelle Spectrometer"],
            acronyms=["TUES"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_UIT = bibcat.Keyword(
            keywords=["Ultraviolet Imaging Telescope"],
            acronyms=["UIT"],
            banned_overlap=[],
            ambig_words=[])
keyword_obj_WUPPE = bibcat.Keyword(
            keywords=["Wisconsin Ultraviolet Photo-Polarimeter Experiment"],
            acronyms=["WUPPE"],
            banned_overlap=[],
            ambig_words=[])
#
kobjs_8set = [keyword_obj_HST, keyword_obj_JWST, keyword_obj_TESS, keyword_obj_Kepler, keyword_obj_PanSTARRS, keyword_obj_GALEX, keyword_obj_K2, keyword_obj_HLA]
#kobjs_all = [keyword_obj_BEFS, keyword_obj_Copernicus, keyword_obj_EUVE, keyword_obj_FIRST, keyword_obj_FUSE, keyword_obj_GALEX, keyword_obj_HLA, keyword_obj_HSC, keyword_obj_HST_expanded, keyword_obj_HUT, keyword_obj_IMAPS, keyword_obj_IUE, keyword_obj_JWST_expanded, keyword_obj_Kepler, keyword_obj_K2, keyword_obj_PanSTARRS, keyword_obj_Roman, keyword_obj_TESS, keyword_obj_TUES, keyword_obj_UIT, keyword_obj_WUPPE]
kobjs_all = [keyword_obj_BEFS, keyword_obj_Copernicus, keyword_obj_EUVE, keyword_obj_FUSE, keyword_obj_GALEX, keyword_obj_HLA, keyword_obj_HSC, keyword_obj_HST_expanded, keyword_obj_HUT, keyword_obj_IMAPS, keyword_obj_IUE, keyword_obj_JWST_expanded, keyword_obj_Kepler, keyword_obj_K2, keyword_obj_PanSTARRS, keyword_obj_Roman, keyword_obj_TESS, keyword_obj_TUES, keyword_obj_UIT, keyword_obj_WUPPE]
#

##Classification mapping parameters
allowed_classifications = ["SCIENCE", "DATA_INFLUENCED", "MENTION", "SUPERMENTION"]
map_papertypes = {"science":"science", "mention":"mention", "supermention":"mention", "data_influenced":"data_influenced", "unresolved_grey":"other", "unresolved_gray":"other", "engineering":"other", "instrument":"other"}
#
